apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-advanced
spec:
  interval: "3m"
  subscriptions:
  - image:
      repoURL: vojtechmaresnotino/guestbook
      imageSelectionStrategy: SemVer
      allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
      strictSemvers: false
  - git:
      repoURL: https://github.com/vojtech-mares_notino/argocd-poc-kargo-v2.git
      branch: main
      strictSemvers: true
