apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd-poc
spec:
  generators:
  - git:
      repoURL: https://github.com/vojtechmares/argocd-poc-kargo-advanced.git
      revision: HEAD
      directories:
      - path: env/*
  template:
    metadata:
      name: guestbook-{{path.basename}}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-advanced:{{path.basename}}
    spec:
      destination:
        namespace: argocd-poc-kargo-{{path.basename}}
        server: "https://kubernetes.default.svc"
      project: guestbook
      source:
        path: ./
        repoURL: https://github.com/vojtechmares/argocd-poc-kargo-advanced.git
        targetRevision: env/{{path.basename}}
